apiVersion: apps/v1
kind: Deployment
metadata:
  name: nftytribe-v2-be
spec:
  replicas: 1
  selector:
    matchLabels:
      nftytribe-v2-dev: api
  template:
    metadata:
      labels:
        nftytribe-v2-dev: api
    spec:
      # volumes:
      #   - name: nftytribe
      #     persistentVolumeClaim:
      #       claimName: nftytribe-be
      containers:
        - name: nftytribe-v2-api
          resources:
            requests:
              cpu: 200m
              memory: 250Mi
          image: radianceobi/nftytribe-v2-be
          ports:
            - containerPort: 4000
          # volumeMounts:
          #   - mountPath: /logs
          #     name: nftytribe
          env:
            - name: redis
              value: redis-service

            - name: db_username
              valueFrom:
                secretKeyRef:
                  name: nftytribe-be
                  key: db_username

            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: nftytribe-be
                  key: db_password

            - name: db_host
              valueFrom:
                secretKeyRef:
                  name: nftytribe-be
                  key: db_host

            - name: db_port
              valueFrom:
                secretKeyRef:
                  name: nftytribe-be
                  key: db_port

            - name: database
              valueFrom:
                secretKeyRef:
                  name: nftytribe-be
                  key: database
