apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nftytribe-v2-be-networks
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: dev.api.v2.nftytribe.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nftytribe-v2-be-cluster-ip-service
                port:
                  number: 4000
