apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      # volumes:
      #   - name: sql-vol
      #     persistentVolumeClaim:
      #       claimName: sql-pvc
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nftytribev2secret
                  key: db_password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: nftytribev2secret
                  key: db_name
          # volumeMounts:
          #   - mountPath: /var/lib/mysql
          #     name: sql-vol
