apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pvc
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName:
